### ISSUE TITLE
The capability to test snap and plugins locally

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap-pluginsync#24]
I would like to be able to "make" binary for my default dev platform so that I can test Snap and plugins locally.

Starting yesterday, I was not able to load plugins locally.

**Comment by mjbrender** [comment]
Hey @candysmurf - could you list what commands you ran, the plugins you tried and the error you receive? I wonder if something changed in the make file during sync and we missed a breaking change. Let's figure it out ⛳️       🏌️

**Comment by nanliu** [comment]
@candysmurf we added some new capabilities to build both osx/linux binaries. The new large test also allows local testing as long you had docker/docker-compose installed. Let me know if this met your requirements, or if there's still a feature gap.

**Comment by candysmurf** [comment]
@mjbrender, I was running tests locally on Mac. It didn't have mac build at the time. It's fine now

@nanliu, yes, it's good and works as expected. We can close this issue. thanks.
