### ISSUE TITLE
The github issue template should request the version of snapd

### ISSUE THREAD

**Issue by jcooklin** [intelsdi-x/snap-pluginsync#25]
Currently we ask for the snapd version by suggesting that the user run `snapctl --version` however this returns the client version and not the version of snapd.

This issue relates to https://github.com/intelsdi-x/snap/issues/1244 which requests that `snapctl` also report the snapd version.

**Comment by mjbrender** [comment]
This was fixed in 4d8f2de205a43 and I missed tagging the issue. Closing 👌
