### ISSUE TITLE
Clean up containers after failed test

### ISSUE THREAD

**Issue by kjlyon** [intelsdi-x/snap-pluginsync#66]
**ToDo:**
We need to add a trap to kill old containers and clean up after a test has failed OR 
Give a warning that when rerunning a test you are using an old container.

**Situation:**
The behavior below happens when running `make test-medium` on the pluginsync branch of snap-plugin-publisher-influxdb after updating with snap-pluginsync. Running `glide update` passes because it is on my local machine. Running `glide update` in the container will fail if has already failed once before. 

**Expected Behavior:**
When I run a test and something fails to load because of proxy or some other reason, I expect that I can rerun the test and I will be working in a new container. Also, when the test fails from inability to load something the containers remain open, this may present other issues.
 Example: 
<img width="865" alt="screenshot" src="https://cloud.githubusercontent.com/assets/21182867/22529818/c6178674-e88d-11e6-886f-e304241e51e9.png">

**Actual Behavior:**
When I rerun the test I am dropped back into the old container which failed to load golang.org/x/sys. To fix this I must go into the container, go to the path of that download and delete the existing folder. This will prompt a reinstall of golang.org/x/sys and it will (likely) work this time.

**Comment by nanliu** [comment]
After another look, this is related to existing medium tests. Medium test scripts are not part of the pluginsync, so I'll reopen this issue with snap-plugin-publisher-influxdb.

**Comment by kjlyon** [comment]
Because medium test scripts are not part of pluginsync this issue can be closed.
